### ISSUE TITLE
Ability to set the git revision of polyfill repository

### ISSUE THREAD

**Issue by jiwonz** [CavefulGames/dalbit#8]
Similar to [git dependencies in pesde](https://docs.pesde.dev/reference/manifest/#git), An ability to set the git revision to fetch polyfill repository would be useful for specifying specific versions of polyfills that are needed.

```toml
[polyfill]
repo = "repo url"
rev = "tag or commit"
```
